name: NIS_India

on:
  push:
    tags:
      - 'NIS_*_*'

  workflow_dispatch:

jobs:

  NIS_articles:
    runs-on: ubuntu-latest

    env:
      NIS_FIRST_FORTNIGHT: 1
      NIS_SECOND_FORTNIGHT: 2

    steps:
      - uses: actions/checkout@v2

      - name: setting_up
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:  |
          sudo apt install -y python3 wget zsh
          sudo pip install -r requirements.txt

      - name: set env
        run:  |
          echo ${{ github.ref_name }}
          NIS_TAG=${{ github.ref_name }}
          echo "NIS_MONTH=$(echo ${NIS_TAG} | egrep -o '(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)')" >> $GITHUB_ENV
          echo "NIS_YEAR=$(echo ${NIS_TAG} | egrep -o '202[0-9]')" >> $GITHUB_ENV


      - name: first fortnight
        run:  |
          source .env
          for lang in 1,2,3,4,6,8,9,10,11,13,15,16,18;
          do
            nis $lang ${{ env.NIS_FIRST_FORTNIGHT }} ${{ env.NIS_MONTH }} ${{ env.NIS_YEAR }}
          done
 
      - name: second fortnight
        run:  |
          source .env
          for lang in 1,2,3,4,6,8,9,10,11,13,15,16,18;
          do
            nis $lang ${{ env.NIS_SECOND_FORTNIGHT }} ${{ env.NIS_MONTH }} ${{ env.NIS_YEAR }}
          done

      - name: copy files
        run:  |
          shopt -s globstar
          mkdir -p /home/runner/pdfs
          for i in /home/runner/NIS/**/**.pdf;
          do
            echo $i
            bname=$(basename ${i})
            mv $i /home/runner/pdfs/${bname}
          done

      - name: Create Link text files
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/runner/pdfs/*.pdf"
          token: ${{ secrets.NIS }}
          tag: "NIS_${{ env.NIS_MONTH }}_${{ env.NIS_YEAR }}"
          allowUpdates: true
          body : "NIS articles links for the month of ${{ env.NIS_MONTH }}, ${{ env.NIS_YEAR }}"
