name: NIS_India_Aug_2020

on:
  push:
    tags:
      - 'v2020_Aug'

  workflow_dispatch:

jobs:

  NIS_articles:
    runs-on: ubuntu-latest

    env:
      NIS_LANG: 1
      NIS_FIRST_FORTNIGHT: 1
      NIS_SECOND_FORTNIGHT: 2
      NIS_MONTH: Aug
      NIS_YEAR: 2020

    steps:
      - uses: actions/checkout@v2

      - name: setting_up
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:  |
          sudo apt install -y python3 wget zsh
          sudo pip install -r requirements.txt
          

      - name: first fortnight
        run:  |
          source .env
          nis ${{ env.NIS_LANG }} ${{ env.NIS_FIRST_FORTNIGHT }} ${{ env.NIS_MONTH }} ${{ env.NIS_YEAR }}

      - name: second fortnight
        run:  |
          source .env
          nis ${{ env.NIS_LANG }} ${{ env.NIS_SECOND_FORTNIGHT }} ${{ env.NIS_MONTH }} ${{ env.NIS_YEAR }}

      - name: zipup_first_ft
        run:  |
          cd /home/runner/NIS/${{ env.NIS_YEAR }}/${{ env.NIS_MONTH }}
          zip -r "/home/runner/NIS_ENG_Fortnight_${{ env.NIS_FIRST_FORTNIGHT }}_${{ env.NIS_MONTH }}_${{ env.NIS_YEAR }}.zip" Fortnight_${{ env.NIS_FIRST_FORTNIGHT }}

      - name: zipup_seconf_ft
        run:  |
          cd /home/runner/NIS/${{ env.NIS_YEAR }}/${{ env.NIS_MONTH }}
          zip -r "/home/runner/NIS_ENG_Fortnight_${{ env.NIS_SECOND_FORTNIGHT }}_${{ env.NIS_MONTH }}_${{ env.NIS_YEAR }}.zip" Fortnight_${{ env.NIS_SECOND_FORTNIGHT }}
     
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NIS }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: first fortnight zip
        id: upload-release-asset-f1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NIS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/NIS_ENG_Fortnight_${{ env.NIS_FIRST_FORTNIGHT }}_${{ env.NIS_MONTH }}_${{ env.NIS_YEAR }}.zip
          asset_name: NIS_ENG_Fortnight_${{ env.NIS_FIRST_FORTNIGHT }}_${{ env.NIS_MONTH }}_${{ env.NIS_YEAR }}.zip
          asset_content_type: application/zip

      - name: second fortnight zip
        id: upload-release-asset-f2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NIS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/NIS_ENG_Fortnight_${{ env.NIS_SECOND_FORTNIGHT }}_${{ env.NIS_MONTH }}_${{ env.NIS_YEAR }}.zip
          asset_name: NIS_ENG_Fortnight_${{ env.NIS_SECOND_FORTNIGHT }}_${{ env.NIS_MONTH }}_${{ env.NIS_YEAR }}.zip
          asset_content_type: application/zip
